### ISSUE TITLE
Update the readme on how to run this.

### ISSUE THREAD

**Issue by GuardianOfTheVoid** [marmust/internet-scanner#2]
As the issue states, can you update the readme so it says how to run this code. i would like to try it out but my background is pure python.

**Comment by Joey451-OG** [comment]
To run the build:

1. Download the `internet_scanner_unity_build` folder from the parent directory: [Unity_stuff](https://github.com/marmust/internet-scanner/tree/main/Unity_stuff). 
2. Run `graph renderer.exe`
3. You may get an error saying "Windows Protected Your PC". This is normal, click the `more options` link, then click the `Run Anyway` button.

The build is only for windows however, you're out of luck if you run any other OS.

To open the Unity Project:
1. Make sure Unity is installed properly on your system.
2. Download the `graph renderer unity project` directory from the parent directory: [Unity_stuff](https://github.com/marmust/internet-scanner/tree/main/Unity_stuff)
3. Open the Unity Launcher.
4. Select: "Import and existing project" (The wording might have changed since the last time I used Unity 5+ years ago, but it should be similar).
5. Navigate to where you put your graph renderer unity project` directory and select it. (GitHub will download the folder as a `.zip` so you'll have to unzip it first.
6. Have fun!

Don't let a new language daunt you. Unity is very well documented so you shouldn't have any issues looking up stuff online (or I guess now, asking ChatGPT lol).

**Comment by marmust** [comment]
thank you! very solid readme i will update in a sec

**Comment by GuardianOfTheVoid** [comment]
Thanks guys, closing
